<a href="https://colab.research.google.com/github/anrivers/NumpyBasic/blob/main/TP1/NumpyBasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importar la liberia de pandas y numpy
import pandas as pd
import numpy as np

In [ ]:
#Leer el archivo csv
df = pd.read_csv('Salario_ventas.csv')
#Llamar a la variable df
df

Pais  Edad  Salario Compro
0   France  44.0  72000.0     No
1    Spain  27.0  48000.0    Yes
2  Germany  30.0  54000.0     No
3    Spain  38.0  61000.0     No
4  Germany  40.0      NaN    Yes
5   France  35.0  58000.0    Yes
6    Spain   NaN  52000.0     No
7   France  48.0  79000.0    Yes
8  Germany  50.0  83000.0     No
9   France  37.0  67000.0    Yes

In [ ]:
x=df.iloc[:,0:3].values #Todad las filas de la columna 0 a 3
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
y=df.iloc[:,3].values #todas las filas de las columna 3
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [ ]:
from sklearn.impute import SimpleImputer #Tecnica de importación
imputer=SimpleImputer(missing_values=np.NaN , strategy='mean') #Llamar el método a los valores faltantes y poner la estrategia
imputer= imputer.fit(x[:,1:3]) #Metodo para identidicar las columnas faltantes
x[:,1:3]=imputer.transform(x[:,1:3]) #Se junta lo tranformado y acutializa la tabla
x #Imprimimos variable

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder #Codificamos la variable país para una combinación de código
x_encoder = LabelEncoder()
x[:,0] = x_encoder.fit_transform(x[:,0])
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [ ]:
#CODIFICAMOS VARIABLE PAIS CON EL METODO ONEHOTENCODER
from sklearn.preprocessing import OneHotEncoder
x_HotEncoder= OneHotEncoder(handle_unknown='ignore')
x_enc = pd.DataFrame(x[:,0])
x_enc = x_HotEncoder.fit_transform(x_enc).toarray()
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [ ]:
#CONCATENAR EL DATAFRAME x_enc CON COLUMNAS RESTANTES
x=np.concatenate((x_enc,x[:,1:3]), axis=1)
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [ ]:
y_enoder = LabelEncoder()
y = y_enoder.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])